### ISSUE TITLE
Module cannot be found

### ISSUE THREAD

**Issue by tavurth** [LFBVR/camera.js#1]
```
import Camera from 'lfcamera';
```
Fails with `module not found` error in webpack 2.x

Suggest changing the docs to show the following:
```
import Camera from 'lfcamera/src/index';
```

Or move the `index.js` to the `lfcamera` directory.

**Comment by gautier-lefebvre** [comment]
@mlefebvresopra Looks like you forgot to remove `lib/` from `.npmignore`.
